version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:5000" # Map the container's port 5000 to the host's port 80 (standard HTTP port)
    environment:
      MONGO_URL: mongodb://db:27017/songManager
      PORT: 5000
    depends_on:
      - db
    restart: always # Ensure the app restarts automatically on failure
    networks:
      - app-network

  db:
    image: mongo:6.0.3 # Use a specific version of MongoDB for stability
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db # Use named volumes for better data management
    restart: always # Ensure the database restarts automatically on failure
    networks:
      - app-network

networks:
  app-network: # Define a network for communication between services

volumes:
  db_data: # Define a named volume for MongoDB data storage
